
steps:




# This is a basic workflow to help you get started with Actions

name: Controller Monitoring

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
 
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version' # Read python version from a file
          
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt  # this is optional

      # Runs a single command using the runners shell
      - name: Run controller monitoring notebook
        run: jupyter nbconvert --to notebook --execute controller/Controller\ Monitoring.ipynb
        
      - name: Commit changes
      - uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub Actions logo
          committer_name: GitHub Actions
          committer_email: actions@github.com
